-- Create categories table
create table categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create videos table
create table videos (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  url text not null, -- URL to YouTube/Vimeo
  thumbnail_url text,
  category_id bigint references categories(id),
  published_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create tags table
create table tags (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create video_tags join table
create table video_tags (
  video_id bigint references videos(id) on delete cascade,
  tag_id bigint references tags(id) on delete cascade,
  primary key (video_id, tag_id)
);

-- Enable Row Level Security (RLS)
alter table categories enable row level security;
alter table videos enable row level security;
alter table tags enable row level security;
alter table video_tags enable row level security;

-- Create policies (Public read access)
create policy "Public categories are viewable by everyone." on categories for select using (true);
create policy "Public videos are viewable by everyone." on videos for select using (true);
create policy "Public tags are viewable by everyone." on tags for select using (true);
create policy "Public video_tags are viewable by everyone." on video_tags for select using (true);

-- Insertar datos de prueba (MUY IMPORTANTE PARA VER ALGO EN PANTALLA)
INSERT INTO categories (name, slug) VALUES 
('Historia', 'historia'),
('Naturaleza', 'naturaleza');

INSERT INTO videos (title, description, url, category_id, thumbnail_url) VALUES 
('La Colonización del Baker', 'Un documental sobre los primeros pobladores.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 1, 'https://images.unsplash.com/photo-1445584860055-096410e42823'),
('Glaciares de la Patagonia', 'Explorando los campos de hielo norte y sur.', 'https://vimeo.com/76979871', 2, 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1');
